name: Deploy Frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - "vite-app/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy frontend via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/chat-application

            git pull origin main

            docker compose build frontend
            docker compose up -d frontend